version: '3.4'
services:
  kafka:
      image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
      container_name: kafka
      command:
        - redpanda
        - start
        - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
        - --advertise-kafka-addr internal://kafka:9092,external://localhost:19092
        - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
        - --advertise-pandaproxy-addr internal://kafka:8082,external://localhost:18082
        - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
        - --rpc-addr kafka:33145
        - --advertise-rpc-addr kafka:33145
        - --mode dev-container
        - --smp 1
        - --default-log-level=info
      ports:
        - 19092:19092
  
  zeppelin:
    image: apache/zeppelin:${ZEPPELIN_VERSION}
    platform: linux/amd64
    container_name: zeppelin
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

    volumes:
      - "./${FLINK_FOLDER}:/opt/flink"
      - ./logs:/logs
      - ./notebook:/notebook
    environment:
      FLINK_HOME: /opt/flink
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
